config/routes.rb
Rabel::Application.routes.draw do
  resources :checkins

  root 'welcome#index'
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  patch 'users/update_account' => 'users#update_account', :as => :update_account
  patch 'users/update_password' => 'users#update_password', :as => :update_password
  patch 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 't/:id' => 'topics#show', :as => :t
  get 'topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get 'my/topics' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'
  get 'new_from_home' => 'topics#new_from_home'
  post 'create_from_home' => 'topics#create_from_home'

  patch 'upyun_images' => 'upyun_images#create'

  resources :channels do
    resources :topics do
      member do
        get :move
        get :edit_title
        patch :update_title
      end
    end
  end

  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    patch :toggle_comments_closed
    patch :toggle_sticky
  end

  resources :comments, :bookmarks, :upyun_images, :qiniu_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do
    resources :side_blocks do
      post :sort, :on => :collection
    end

    resources :nav_links do
      post :sort, :on => :collection
    end

    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :channels do
      post :sort, :on => :collection
      get :move, :on => :member
      patch :move_to, :on => :member
    end

    resources :users do
      member do
        patch :toggle_admin
        patch :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root 'welcome_admin#index'
  end
end

app/views/admin/pages/_form.html.haml
= simple_form_for [:admin, page] do |f|
  = f.input :title, :label => '标题'
  .form-group
    = f.label :key, '英文标题'
    .input-group
      %span.input-group-addon /page/
      = f.text_field :key, :class => 'form-control'
    %span.help-block 只允许英文字符和下划线

  .form-group
    = f.label :content, '页面内容'
    = render 'shared/preview_widget', :ref => :page_content, :type => :page
    = f.text_area :content, :class => 'form-control', :rows => 5
  .form-group
    = f.label :published, '发布状态'
    .radio
      %label
        = f.radio_button 'published', true
        %span.published 立刻发布
      %label
        = f.radio_button 'published', false
        %span.draft 保存为草稿
  .form-actions
    = f.submit '保存', :class => 'btn btn-sm btn-primary'

app/views/admin/pages/_page.html.haml
%tr{:id => page.html_id}
  %td{:align => :right, :width => 200}
    = link_to page_real_url(page), page_real_url(page)
  %td{:align => :center, :width => :auto}
    = page.title
  %td{:align => :center, :width => :auto}
    = page_publish_status(page)
  %td{:align => :left}
    = admin_edit_button('修改页面', page)
    = admin_delete_button(page)

app/views/admin/pages/action.html.haml
.box
  .cell
    = build_admin_navigation([link_to('页面管理', admin_pages_path), @title])
  .inner
    = render 'form', :page => @page

app/views/admin/pages/index.html.haml
- content_for :template_js do
  :plain
    rabel.sortable("table tbody", "#{sort_admin_pages_path}", {
      helper: function(e, ui) {
        ui.children().each(function() {
          $(this).width($(this).width());
        });
        return ui;
      }
    })

.box
  .cell
    .fr
      = admin_create_button('创建新页面', :page)
    = build_admin_navigation([@title])
  .inner
    %table.table
      %thead
        %tr
          %th{:align => :right, :width => 100} URL
          %th{:align => :center, :width => :auto} 标题
          %th{:align => :center, :width => :auto} 发布状态
          %th{:align => :left} 操作
      %tbody
        = render @pages