config/routes.rb
Rabel::Application.routes.draw do
  resources :checkins

  root 'welcome#index'
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  patch 'users/update_account' => 'users#update_account', :as => :update_account
  patch 'users/update_password' => 'users#update_password', :as => :update_password
  patch 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 't/:id' => 'topics#show', :as => :t
  get 'topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get 'my/topics' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'
  get 'new_from_home' => 'topics#new_from_home'
  post 'create_from_home' => 'topics#create_from_home'

  patch 'upyun_images' => 'upyun_images#create'

  resources :channels do
    resources :topics do
      member do
        get :move
        get :edit_title
        patch :update_title
      end
    end
  end

  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    patch :toggle_comments_closed
    patch :toggle_sticky
  end

  resources :comments, :bookmarks, :upyun_images, :qiniu_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do
    resources :side_blocks do
      post :sort, :on => :collection
    end

    resources :nav_links do
      post :sort, :on => :collection
    end

    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :channels do
      post :sort, :on => :collection
      get :move, :on => :member
      patch :move_to, :on => :member
    end

    resources :users do
      member do
        patch :toggle_admin
        patch :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root 'welcome_admin#index'
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  include Notifiable

  belongs_to :channel
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :bookmarks, :as => :bookmarkable, :dependent => :destroy
  has_many :notifications, :as => :notifiable, :dependent => :destroy

  validates :title, :presence => true

  before_create :set_default_value

  def last_comment
    self.comments.order('created_at ASC').last
  end

  def locked?
    Time.now - self.created_at > Siteconf.topic_editable_period
  end

  def allow_modification_by?(user)
    (!locked? && self.user == user) || user.can_manage_site?
  end

  def notifiable_title
    title
  end

  def notifiable_path
    "/t/#{id}"
  end

  private

  def set_default_value
    self.hit = 0
    self.involved_at = Time.zone.now
  end
end

app/controllers/admin/topics_controller.rb
# encoding: utf-8
class Admin::TopicsController < Admin::BaseController
  def index
    @topics = Topic.order('created_at DESC').page(params[:page])
    @title = '讨论话题'
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      redirect_to admin_topics_path
    else
      redirect_to admin_root_path
    end
  end
end

app/controllers/topics_controller.rb
# encoding: utf-8
class TopicsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :find_channel, :except => [:show, :index, :preview, :toggle_comments_closed, :toggle_sticky, :new_from_home, :create_from_home]
  before_action :find_topic_and_auth, :only => [:edit_title,:update_title,
    :edit, :update, :move, :destroy]
  before_action :only => [:toggle_comments_closed, :toggle_sticky] do |c|
    auth_admin
  end

  def index
    per_page = 20
    @title = '全站最新更改记录'
    if params[:page].present?
      current_page = params[:page].to_i
      @title += " (第 #{current_page} 页)"
    else
      current_page = 1
    end

    @topics = Topic.page(current_page).per(per_page).order('updated_at DESC')
  end

  def show
    @topic = Topic.find(params[:id])
    store_location

    Topic.increment_counter(:hit, @topic.id)

    @channel = @topic.channel
    @title = "#{@topic.title} - #{@channel.name}"

    @total_comments = @topic.comments.count
    @total_pages = (@total_comments * 1.0 / Siteconf.pagination_comments.to_i).ceil
    @current_page = params[:p].nil? ? @total_pages : params[:p].to_i
    @per_page = Siteconf.pagination_comments.to_i
    @comments = @topic.comments.page(@current_page).per(@per_page).order('created_at ASC')

    @new_comment = @topic.comments.new
    @total_bookmarks = @topic.bookmarks.count

    @prev_topic = PrevTopicQuery.new(@channel, @topic).get!
    @next_topic = NextTopicQuery.new(@channel, @topic).get!
  end

  def new
    @topic = @channel.topics.new

    @title = build_title('创建新话题')
  end

  def new_from_home
    @topic = Topic.new
    @topic.channel = Channel.find(params[:channel_id]) if params[:channel_id]

    @title = build_title('创建新话题')
    render :layout => 'single-column'
  end

  def create
    if CreateTopic.with(current_user, @channel, topic_params)
      redirect_to t_path(@topic.id)
    else
      render :new
    end
  end

  def create_from_home
    @channel = Channel.find(params[:topic][:channel_id])

    @topic = CreateTopic.with(current_user, @channel, topic_params)
    if @topic
      redirect_to t_path(@topic.id)
    else
      render :new_from_home
    end
  end

  def edit_title
    respond_to do |f|
      f.js
    end
  end

  def update_title
    respond_to do |f|
      f.js {
        unless @topic.update(topic_params)
          render :text => :error, :status => :unprocessable_entity
        end
      }
    end
  end

  def edit
  end

  def update
    if params[:new_channel_id].present?
      # move to new channel
      @new_channel = Channel.find(params[:new_channel_id])
      respond_to do |format|
        format.js {
          if @new_channel.present?
            @topic.channel = @new_channel
            if @topic.save
              render :js => "window.location.reload()"
            else
              render :js => "$.facebox('移动帖子失败')"
            end
          else
            render :js => "$.facebox('节点不存在')"
          end
        }
      end
    else
      if @topic.update(topic_params)
        redirect_to t_path(@topic.id)
      else
        flash[:error] = '之前的更新有误，请编辑后再提交'
        render :edit
      end
    end
  end

  def move
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @topic.destroy
      redirect_to root_path, :notice => '帖子删除成功'
    else
      raise RuntimeError.new('删除帖子出错')
    end
  end

  def preview
    @type = ['topic', 'comment', 'page'].delete params[:type]
    respond_to do |f|
      if @type.present?
        f.text { @content = params[:content] }
      else
        render :text => :error, :status => :unprocessable_entity
      end
    end
  end

  def toggle_comments_closed
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:comments_closed)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  def toggle_sticky
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:sticky)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  private
    def find_channel
      @channel = Channel.find(params[:channel_id])
    end

    def find_topic_and_auth
      @topic = @channel.topics.find(params[:id])
      authorize! :update, @topic, :message => '你没有权限管理此主题'
    end

    def topic_params
      if current_user.can_manage_site?
        params.require(:topic).permit(:title, :content, :comments_closed, :sticky)
      else
        params.require(:topic).permit(:title, :content)
      end
    end
end

app/views/topics/_back_to_channel.html.haml
%span.fade
  %span.chevron ‹&nbsp;
  返回
  = link_to channel.name, channel

app/views/topics/_form.html.haml
.alert.alert-info 如果标题已经包含你想说的话，内容可以留空
= simple_form_for [channel, topic] do |f|
  = f.input :title, :label => '标题', :input_html => {:maxlength => 150, :class => :span6}
  = render 'shared/fileupload_widget', :textarea_selector => "textarea#topic_content"
  = render 'shared/preview_widget', :ref => :topic_content, :type => :topic
  = f.input :content, :input_html => {:rows => 10}, :label => false, :placeholder => '话题内容'
  - if current_user.can_manage_site?
    .checkbox
      = f.input :sticky, :inline_label => '保持置顶', :label => false
    .checkbox
      = f.input :comments_closed, :inline_label => '禁止回复', :label => false
  = f.submit (topic.new_record? ? '创建新话题' : '提交修改'), :class => 'btn btn-primary', :data => {:disable_with => t('tips.submitting')}

app/views/topics/_move_form.js.haml
= form_for [@channel, @topic], :remote => :true do |f|
  = label_tag '移动到新讨论区'
  .sep10
  = select_tag "new_channel_id", options_from_collection_for_select(Channel.default_order.all, :id, :name, f.object.channel.id)
  .sep10
  = f.submit '开始移动', :class => 'btn btn-sm btn-success'

app/views/topics/_profile_topic.html.haml
- channel = topic.channel
- comments_count = topic.comments.count
- last_replied_by = topic.last_replied_by
.cell.topic{:class => topic_user.can_manage_site? ? 'admin' : ''}
  %table{:cellpadding => 0, :cellspacing => 0, :border => 0, :width => '100%'}
    %tr
      %td{:valign => :middle, :width => :auto}
        %span.bigger
          = link_to topic.title, t_path(topic.id), :class => 'rabel topic'
        .topic-meta
          = link_to channel.name, channel, :class => 'dark rabel channel'
          - if comments_count > 0
            &nbsp;&nbsp;•&nbsp;&nbsp;
            = time_ago_in_words(topic.last_replied_at)
            &nbsp;&nbsp;•&nbsp;&nbsp;
            最后回复来自
            = nickname_profile_link(last_replied_by)
          - else
            &nbsp;&nbsp;•&nbsp;&nbsp;
            = time_ago_in_words(topic.created_at)
      %td{:valign => :middle, :width => 40, :align => :right}
        .badge.badge-info= comments_count

app/views/topics/_table_view.html.haml
%table{:cellpadding => 5, :cellspacing => 0, :border => 0, :width => '100%', :class => :topics}
  %tr
    %th{:align => :right, :width => 50} 回复
    %th{:align => :left, :width => :auto} 标题
    %th{:align => :left, :width => 200, :colspan => 2} 最后回复时间
  - i = 1
  - topics.each do |topic|
    - class_name = (i % 2 == 0) ? 'even' : 'odd'
    - i += 1
    %tr
      %td{:align => :right, :width => 50, :class => "#{class_name} lend"}
        - comments_count = topic.comments.count
        - if comments_count > 0
          %strong
            %span.green= comments_count
        - else
          %span.snow 0
      %td{:align => :left, :width => :auto, :class => class_name}
        = link_to topic.title, t_path(topic.id)
      - last_comment = topic.last_comment
      - last_comment = topic if last_comment.nil?
      %td{:align => :left, :width => 80, :class => class_name}
        = user_profile_link(last_comment.user, :class => :dark)
      %td{:align => :left, :width => 120, :class => "#{class_name} rend"}
        %small.fade= last_comment.created_at.strftime("%Y-%m-%d %H:%M:%S")

app/views/topics/_title_form.html.haml
= form_for [@channel, @topic], :url => update_title_channel_topic_path(@channel, @topic), :remote => true do |f|
  %a{:name => 'new_topic'}
  = f.label :title, '标题'
  .sep5
  = f.text_area :title, :class => 'form-control', :rows => 2, :autofocus => true
  .sep5
  = f.submit '提交修改', :class => 'btn btn-small btn-success', :data => {:disable_with => t('tips.submitting')}

app/views/topics/_topic.html.haml
- topic_user = topic.user
- channel = topic.channel
- comments_count = topic.comments.count
- last_replied_by = topic.last_replied_by
.cell.topic{:class => topic_user.can_manage_site? ? 'admin' : ''}
  .avatar.float-left
    = user_profile_avatar_link(topic_user, :medium)
  .item_title
    - if comments_count > 0
      .float-right
        .badge.badge-info= comments_count
    %h2.topic_title
      = link_to topic.title, t_path(topic.id), :class => 'rabel topic'
    .topic-meta
      = link_to channel.name, channel, :class => 'dark rabel channel'
      %span.muted •
      = user_profile_link(topic_user, :class => :dark)
      %span.muted •
      - if comments_count > 0
        -# = time_ago_in_words(topic.last_replied_at)
        = time_ago_in_words(Time.now)
        %span.muted •
        最后回复来自
        = nickname_profile_link(last_replied_by)
      - else
        = time_ago_in_words(topic.created_at)

app/views/topics/edit_title.js.haml
$.facebox("#{escape_javascript(render('title_form'))}")

app/views/topics/index.html.haml
.box
  .cell= build_navigation([@title])
  = render @topics
  .inner{:align => :center}
    = paginate @topics

app/views/topics/new.html.haml
.box
  .cell
    = build_navigation [link_to(@node.name, go_path(@node.key))]
  .inner
    %h2 创建新话题
    = render 'form', :node => @node, :topic => @topic, :comments_closed => false

app/views/topics/new_from_home.html.slim
.box
  .cell
    h2 创建新话题
  .inner
    = simple_form_for @topic, :url => create_from_home_path do |f|
      = f.input :title, :label => '标题', :input_html => {:maxlength => 150, :class => :span6}
      = render 'shared/fileupload_widget', :textarea_selector => "textarea#topic_content"
      = render 'shared/preview_widget', :ref => :topic_content, :type => :topic
      = f.input :content, :input_html => {:rows => 10}, :label => false, :placeholder => '话题内容'
      = f.association :channel, :label => false, :collection => Channel.order('created_at ASC').all, :prompt => '选择讨论区'
      - if current_user.can_manage_site?
        .checkbox
          = f.input :sticky, :inline_label => '保持置顶', :label => false
        .checkbox
          = f.input :comments_closed, :inline_label => '禁止回复', :label => false
      = f.submit '创建新话题', :class => 'btn btn-primary btn-inverse', :data => {:disable_with => t('tips.submitting')}

app/views/topics/preview.text.haml
- format_method = "format_#{@type}"
= send(format_method, @content)

app/views/topics/show.html.haml
= render 'topics/show/bookmarked_users'
= render 'topics/show/manage'

- content_for :sidebar_box do
  = render OtherSideBlocksQuery.new.get!

- content_for :template_js do
  :plain
    var creating_comment = false;

    $("textarea#comment_content").keydown(function(e) {
      if (e.ctrlKey && e.keyCode == 13) {
        if (creating_comment) return;
        creating_comment = true
        $("input[type=submit]").click();
      }
    });

- topic_user = @topic.user

.box
  %article
    .header
      .float-right
        = user_profile_avatar_link(topic_user, :large)
      = build_navigation([link_to(@channel.name, @channel, :class => :rabel)], 'bigger')
      .sep10
      %h1#topic_title
        = Rabel::Base.make_mention_links(Rabel::Base.h(@topic.title)).html_safe
      %small.topic-meta
        By
        = user_profile_link(topic_user, :class => :dark)
        at
        = time_ago_in_words(@topic.created_at)
        ,
        = @topic.hit
        次浏览
      .clearfix
    .inner
      .content.topic_content= format_topic(@topic.content)
      - if user_signed_in?
        .float-right
          - if current_user.bookmarked?(@topic)
            = link_to '取消收藏', current_user.bookmark_of(@topic), :method => :delete, :class => 'btn btn-xs btn-info unbookmark'
          - else
            = link_to '加入收藏', topic_bookmarks_path(@topic), :method => :post, :class => 'btn btn-xs btn-info bookmark'
      .clearfix
    .inner
      - if @next_topic.present?
        .float-right
          = link_to proper_length(@next_topic.title, 15), t_path(@next_topic.id), :class => :rabel, :rel => :prev
          %span.guillemet.right-guillemet »

      - if @prev_topic.present?
        .float-left
          %span.guillemet.left-guillemet «
          = link_to proper_length(@prev_topic.title, 15), t_path(@prev_topic.id), :class => :rabel, :rel => :next
      .clearfix

= render 'topics/show/comments' if @comments.any?

- if @topic.comments_closed?
  = render 'shared/box_tip', :tip => t('tips.comments_closed')
- elsif @comments.empty?
  = render 'shared/box_tip', :tip => '目前尚无回复'

= render 'topics/show/comment_form' unless @topic.comments_closed?

app/views/topics/update_title.js.haml
$("#topic_title").html("#{escape_javascript(@topic.title)}");
$.facebox.close();