config/routes.rb
Rabel::Application.routes.draw do
  resources :checkins

  root 'welcome#index'
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  patch 'users/update_account' => 'users#update_account', :as => :update_account
  patch 'users/update_password' => 'users#update_password', :as => :update_password
  patch 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 't/:id' => 'topics#show', :as => :t
  get 'topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get 'my/topics' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'
  get 'new_from_home' => 'topics#new_from_home'
  post 'create_from_home' => 'topics#create_from_home'

  patch 'upyun_images' => 'upyun_images#create'

  resources :channels do
    resources :topics do
      member do
        get :move
        get :edit_title
        patch :update_title
      end
    end
  end

  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    patch :toggle_comments_closed
    patch :toggle_sticky
  end

  resources :comments, :bookmarks, :upyun_images, :qiniu_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do
    resources :side_blocks do
      post :sort, :on => :collection
    end

    resources :nav_links do
      post :sort, :on => :collection
    end

    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :channels do
      post :sort, :on => :collection
      get :move, :on => :member
      patch :move_to, :on => :member
    end

    resources :users do
      member do
        patch :toggle_admin
        patch :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root 'welcome_admin#index'
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  include Notifiable

  belongs_to :channel
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :bookmarks, :as => :bookmarkable, :dependent => :destroy
  has_many :notifications, :as => :notifiable, :dependent => :destroy

  validates :title, :presence => true

  before_create :set_default_value

  def last_comment
    self.comments.order('created_at ASC').last
  end

  def locked?
    Time.now - self.created_at > Siteconf.topic_editable_period
  end

  def allow_modification_by?(user)
    (!locked? && self.user == user) || user.can_manage_site?
  end

  def notifiable_title
    title
  end

  def notifiable_path
    "/t/#{id}"
  end

  private

  def set_default_value
    self.hit = 0
    self.involved_at = Time.zone.now
  end
end

app/controllers/admin/topics_controller.rb
# encoding: utf-8
class Admin::TopicsController < Admin::BaseController
  def index
    @topics = Topic.order('created_at DESC').page(params[:page])
    @title = '讨论话题'
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      redirect_to admin_topics_path
    else
      redirect_to admin_root_path
    end
  end
end

app/controllers/topics_controller.rb
# encoding: utf-8
class TopicsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :find_channel, :except => [:show, :index, :preview, :toggle_comments_closed, :toggle_sticky, :new_from_home, :create_from_home]
  before_action :find_topic_and_auth, :only => [:edit_title,:update_title,
    :edit, :update, :move, :destroy]
  before_action :only => [:toggle_comments_closed, :toggle_sticky] do |c|
    auth_admin
  end

  def index
    per_page = 20
    @title = '全站最新更改记录'
    if params[:page].present?
      current_page = params[:page].to_i
      @title += " (第 #{current_page} 页)"
    else
      current_page = 1
    end

    @topics = Topic.page(current_page).per(per_page).order('updated_at DESC')
  end

  def show
    @topic = Topic.find(params[:id])
    store_location

    Topic.increment_counter(:hit, @topic.id)

    @channel = @topic.channel
    @title = "#{@topic.title} - #{@channel.name}"

    @total_comments = @topic.comments.count
    @total_pages = (@total_comments * 1.0 / Siteconf.pagination_comments.to_i).ceil
    @current_page = params[:p].nil? ? @total_pages : params[:p].to_i
    @per_page = Siteconf.pagination_comments.to_i
    @comments = @topic.comments.page(@current_page).per(@per_page).order('created_at ASC')

    @new_comment = @topic.comments.new
    @total_bookmarks = @topic.bookmarks.count

    @prev_topic = PrevTopicQuery.new(@channel, @topic).get!
    @next_topic = NextTopicQuery.new(@channel, @topic).get!
  end

  def new
    @topic = @channel.topics.new

    @title = build_title('创建新话题')
  end

  def new_from_home
    @topic = Topic.new
    @topic.channel = Channel.find(params[:channel_id]) if params[:channel_id]

    @title = build_title('创建新话题')
    render :layout => 'single-column'
  end

  def create
    if CreateTopic.with(current_user, @channel, topic_params)
      redirect_to t_path(@topic.id)
    else
      render :new
    end
  end

  def create_from_home
    @channel = Channel.find(params[:topic][:channel_id])

    @topic = CreateTopic.with(current_user, @channel, topic_params)
    if @topic
      redirect_to t_path(@topic.id)
    else
      render :new_from_home
    end
  end

  def edit_title
    respond_to do |f|
      f.js
    end
  end

  def update_title
    respond_to do |f|
      f.js {
        unless @topic.update(topic_params)
          render :text => :error, :status => :unprocessable_entity
        end
      }
    end
  end

  def edit
  end

  def update
    if params[:new_channel_id].present?
      # move to new channel
      @new_channel = Channel.find(params[:new_channel_id])
      respond_to do |format|
        format.js {
          if @new_channel.present?
            @topic.channel = @new_channel
            if @topic.save
              render :js => "window.location.reload()"
            else
              render :js => "$.facebox('移动帖子失败')"
            end
          else
            render :js => "$.facebox('节点不存在')"
          end
        }
      end
    else
      if @topic.update(topic_params)
        redirect_to t_path(@topic.id)
      else
        flash[:error] = '之前的更新有误，请编辑后再提交'
        render :edit
      end
    end
  end

  def move
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @topic.destroy
      redirect_to root_path, :notice => '帖子删除成功'
    else
      raise RuntimeError.new('删除帖子出错')
    end
  end

  def preview
    @type = ['topic', 'comment', 'page'].delete params[:type]
    respond_to do |f|
      if @type.present?
        f.text { @content = params[:content] }
      else
        render :text => :error, :status => :unprocessable_entity
      end
    end
  end

  def toggle_comments_closed
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:comments_closed)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  def toggle_sticky
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:sticky)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  private
    def find_channel
      @channel = Channel.find(params[:channel_id])
    end

    def find_topic_and_auth
      @topic = @channel.topics.find(params[:id])
      authorize! :update, @topic, :message => '你没有权限管理此主题'
    end

    def topic_params
      if current_user.can_manage_site?
        params.require(:topic).permit(:title, :content, :comments_closed, :sticky)
      else
        params.require(:topic).permit(:title, :content)
      end
    end
end

app/views/topics/show/_bookmark_button.html.haml
- if user_signed_in?
  .inner
    .fr{:align => :right}
      - if current_user.bookmarked?(@topic)
        = link_to '取消收藏', current_user.bookmark_of(@topic), :method => :delete, :class => 'op cancel'
      - else
        = link_to '加入收藏', topic_bookmarks_path(@topic), :method => :post, :class => :op
    &nbsp;&nbsp;

app/views/topics/show/_bookmarked_users.html.haml
- if @total_bookmarks > 0
  - content_for :rightbar do
    .box
      .header
        收藏此话题的成员
      .inner
        - @topic.bookmarks.each do |b|
          = user_profile_avatar_link(b.user, :mini)

app/views/topics/show/_comment_form.html.haml
- if user_signed_in?
  = form_for [@topic, @new_comment] do |f|
    .box
      .header
        .fr
          ⬆
          = link_to '回到顶部', 'javascript:void(0);', :class => 'dark back_to_top'
        现在就添加一条回复
      .inner
        = render 'shared/fileupload_widget', :textarea_selector => "textarea#comment_content"
        = render 'shared/preview_widget', :ref => :comment_content, :type => :comment
        = f.text_area :content, :rows => 5, :style => 'width: 100%;', :class => 'form-control'
        .sep10
        = f.submit '发送', :class => 'btn btn-sm btn-success', :data => {:disable_with => t('tips.submitting')}
        %small.gray 支持 Ctrl + Enter 快捷键

app/views/topics/show/_comments.html.haml
%section
  .box
    .header
      .fr
        - if @topic.comments_closed?
          回复权限关闭
        - else
          ⬇
          = link_to '跳到回复', 'javascript:void(0);', :class => 'dark jump_to_comment'
      = "#{@total_comments} 回复"
    #replies{:class => "#{'fix_cell' if @total_pages == 1}"}
      = render @comments
    .center
      = paginate @comments, :param_name => :p

app/views/topics/show/_manage.html.slim
- if can? :update, @topic
  - content_for :sidebar_box do
    .box
      .cell
        .dropdown
          = link_to '话题管理', 'javascript:void(0);', class: 'dropdown-toggle btn btn-block btn-sm btn-info', data: {toggle: 'dropdown'}
          ul.dropdown-menu
            li= link_to '修改标题', edit_title_channel_topic_path(@channel, @topic), :remote => true
            li= link_to '编辑全部', edit_channel_topic_path(@channel, @topic)
            li.divider
            li= link_to '移动到新讨论区', move_channel_topic_path(@channel, @topic), :remote => true
            - if current_user.can_manage_site?
              - toggle_comments_closed_tip = @topic.comments_closed? ? '允许回复' : '禁止回复'
              li= link_to toggle_comments_closed_tip, topic_toggle_comments_closed_path(@topic), :method => :patch
              - toggle_sticky_tip = @topic.sticky? ? '取消置顶' : '置顶此话题'
              li= link_to toggle_sticky_tip, topic_toggle_sticky_path(@topic), :method => :patch
            li.divider
            li= link_to '删除此话题', channel_topic_path(@channel, @topic), :method => :delete, :data => {:confirm => t(:delete_confirm)}