config/routes.rb
Rabel::Application.routes.draw do
  resources :checkins

  root 'welcome#index'
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  patch 'users/update_account' => 'users#update_account', :as => :update_account
  patch 'users/update_password' => 'users#update_password', :as => :update_password
  patch 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 't/:id' => 'topics#show', :as => :t
  get 'topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get 'my/topics' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'
  get 'new_from_home' => 'topics#new_from_home'
  post 'create_from_home' => 'topics#create_from_home'

  patch 'upyun_images' => 'upyun_images#create'

  resources :channels do
    resources :topics do
      member do
        get :move
        get :edit_title
        patch :update_title
      end
    end
  end

  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    patch :toggle_comments_closed
    patch :toggle_sticky
  end

  resources :comments, :bookmarks, :upyun_images, :qiniu_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do
    resources :side_blocks do
      post :sort, :on => :collection
    end

    resources :nav_links do
      post :sort, :on => :collection
    end

    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :channels do
      post :sort, :on => :collection
      get :move, :on => :member
      patch :move_to, :on => :member
    end

    resources :users do
      member do
        patch :toggle_admin
        patch :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root 'welcome_admin#index'
  end
end

app/views/shared/_ad.html.haml
.box
  .inner
    %span{:style => 'font-weight: bold; font-size: 10px; color: #e2e2e2;'} Promotion
    .sep10
    = link_to ad.link, :class => :track_event, :target => '_blank', :data => {:category => :ad, :action => :click, :label => ad.title} do
      = image_tag ad.banner.url, :border => 0, :width => 120, :height => 90
    .sep5
    %span{:style => 'font-size: 11px; color: #666;'}
      %strong{:style => 'color: #000;'}
        = link_to ad.title, ad.link, :target => '_blank', :class => 'black track_event', :data => {:category => :ad, :action => :click, :label => ad.title}
    .sep3
    %span{:style => 'font-size: 12px;'}= ad.words

app/views/shared/_alert.html.haml
- if flash[:notice].present?
  %p.alert.alert-info= notice
- if flash[:success].present?
  %p.alert.alert-success= flash[:success]
- if flash[:alert].present?
  %p.alert.alert-error= flash[:alert]

app/views/shared/_box_tip.html.haml
.glass
  .inner.center
    = tip

app/views/shared/_content.html.haml
- if flash_messages.any?
  .box
    .inner
      = show_flash_messages
= yield

app/views/shared/_fileupload_widget.html.haml
- if Figaro.env.RABEL_UPYUN_SWITCH == 'on'
  - content_for :final_head do
    = javascript_include_tag 'i_fileupload'

  - content_for :template_js do
    :plain
      var textarea = $("#{textarea_selector}");
      var _tip = $("#upload-tip");
      $('#fileupload').fileupload({
          dataType: 'json',
          autoUpload: true,
          url: '/upyun_images.json',
          maxFileSize: 1024 * 1024 * 5,
          acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
          start: function(e) {
            _tip.html('图片上传中&nbsp;&middot;&middot;&middot;');
          },
          done: function (e, data) {
              $.each(data.result, function (index, file) {
                new_pic = "\n" + file.url;
                textarea.atCaret('insert', new_pic);
              });
          },
          always: function(e) {
            _tip.html("上传图片");
          },
      });

  .float-right
    %a.fileupload-btn.action_label
      %span#upload-tip 上传图片
      %input#fileupload{:type => 'file', :multiple => true, :name => "upyun_image[asset][]"}

- if Figaro.env.RABEL_QINIU_SWITCH == 'on'
  - content_for :final_head do
    = javascript_include_tag 'i_fileupload'

  - content_for :template_js do
    :plain
      var textarea = $("#{textarea_selector}");
      var _tip = $("#upload-tip");
      $('#fileupload').fileupload({
          dataType: 'json',
          autoUpload: true,
          url: '/qiniu_images.json',
          maxFileSize: 1024 * 1024 * 5,
          acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
          start: function(e) {
            _tip.html('图片上传中&nbsp;&middot;&middot;&middot;');
          },
          done: function (e, data) {
              $.each(data.result, function (index, file) {
                new_pic = "\n" + file.url;
                textarea.atCaret('insert', new_pic);
              });
          },
          always: function(e) {
            _tip.html("上传图片");
          },
      });

  .float-right
    %a.fileupload-btn.action_label
      %span#upload-tip 上传图片
      %input#fileupload{:type => 'file', :multiple => true, :name => "qiniu_image[asset][]"}

app/views/shared/_footer.html.haml
#footer
  .container#footer-main
    %strong.page-links
      = render :partial => 'pages/nav', :collection => Page.only_published.default_order, :spacer_template => 'pages/nav_ruler'
    .copywrite
      = Siteconf.footer.html_safe

= render 'shared/google_analytics'

:javascript
  window.rabel = {
    search_engine_url: "#{search_engine_url}",
    version: "#{Rabel.version}"
  };
  jQuery(function($) {
    #{yield :template_js}
  });

:javascript
  #{Siteconf.custom_js.html_safe}

app/views/shared/_google_analytics.html.haml
- if Rails.env.production? and Siteconf.ga_id.present?
  %script{:type => 'text/javascript'}
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '#{Siteconf.ga_id}']);
    _gaq.push(['_trackPageview']);
    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
- else
  / Google Analytics tracking code goes here

app/views/shared/_head.html.haml
= render 'shared/meta'
= stylesheet_link_tag "application"
= yield :head
- if Siteconf.theme != 'default'
  = stylesheet_link_tag "#{Siteconf.theme}/i_theme"
- if Siteconf.custom_css.present?
  %style{:type => 'text/css'}= Siteconf.custom_css.html_safe
= javascript_include_tag "application"
= yield :final_head

app/views/shared/_meta.html.slim
meta charset="UTF-8"
meta name="HandheldFriendly" content="True"
meta name="viewport" content="width=device-width, initial-scale=1.0"
= yield :custom_meta
= csrf_meta_tags
title= @title
= Siteconf.custom_head_tags.html_safe
= favicon_link_tag "/favicon.ico"

app/views/shared/_notification.html.haml
- action_user = notification.action_user
.cell.notification
  %table{:width => '100%'}
    %tr
      %td{:width => 32, :align => :left, :valign => :top}
        = user_profile_avatar_link(action_user, :mini)
      %td{:valign => :top}
        %span.gray
          %strong= user_profile_link(action_user)
          - if notification.action == Notification::ACTION_REWARD
            - if notification.notifiable.amount > 0
              %span.green 奖励给你
            - else
              %span.red 从你的帐户中扣除了
            %strong= notification.notifiable.amount.abs
            = Siteconf.reward_title
          - else
            = notification.action_info_prefix
            = link_to notification.notifiable.notifiable_title, read_notification_path(notification), :class => :rabel
            = notification.action_info_suffix + '了你'
        %span.snow
          = time_ago_in_words(notification.created_at)
        .sep5
        - if notification.content.present?
          .payload= parse_markdown(notification.content)

app/views/shared/_preview_widget.html.haml
#preview-widget
  = link_to '编辑', 'javascript:void(0);', :class => 'action_label cancel_preview current_label', :data => {:ref => ref}
  = link_to '预览', 'javascript:void(0);', :class => 'action_label preview', :data => {:ref => ref, :type => type}
  #preview

app/views/shared/_rss.html.haml
= image_tag 'rss.png', :align => :absmiddle
= link_to 'RSS', topics_path(:atom), :target => '_blank', :class => :dark

app/views/shared/_top.html.haml
#TopMain
  - if Siteconf.custom_logo.present?
    = link_to root_path, :class => 'logo custom_logo' do
      = image_tag Siteconf.custom_logo, :alt => :logo
  - else
    = link_to Siteconf.site_name, root_path, :class => 'logo text_logo'
  #Navigation
    %ul
      %li= link_to '首页', root_path, :class => link_class
      - if user_signed_in?
        %li= user_profile_link(current_user, :class => link_class)
        %li= link_to '个人设置', settings_path, :class => link_class
        - if current_user.can_manage_site?
          %li= link_to '管理后台', admin_root_path, :class => link_class
        %li= link_to '登出', destroy_user_session_path, :method => :delete, :class => link_class
      - else
        %li= link_to '注册', new_user_registration_path, :class => link_class
        %li= link_to '登入', new_user_session_path, :class => link_class
  #Search
    .search_input
      %input#q{:type => 'text', :maxlength => 40, :name => 'q', :data => {:domain => Siteconf.site_host}}

app/views/shared/_user_sidebar_box.html.slim
.box
  .header
    .float-right
      = Siteconf.slogan
    strong= Siteconf.site_name
  .cell
    .row
      .col-md-6.center style="border-right: 1px solid #9d9d9d;"
        = link_to my_topics_path, class: 'rabel' do
          h2= current_user.bookmarked_topics_count
          |话题收藏
      .col-md-6.center
        = link_to my_following_path, class: 'rabel' do
          h2= current_user.followed_user_count
          |特别关注
  .cell
    = link_to new_from_home_path, class: 'rabel' do
      span.glyphicon.glyphicon-edit
      |&nbsp;发布主题
  .cell
    .float-right
      span.checkin_status 连续签到#{current_user.continuous_checkins}次，累计#{current_user.checkins_count}次
    - if CheckedInAtQuery.new(current_user, Date.today).get!
      = link_to '今日已签到', 'javascript:void(0);', class: 'checkin_btn'
    - else
      = link_to '今日签到', checkins_path, method: :post, class: 'checkin_btn'
  .inner
    = link_to "#{@unread_count} 条未读消息", notifications_path, class: 'rabel'